version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - NODE_ENV=production
    volumes:
      - ./don-sanity-backend:/var/www/html
      - ./don-sanity-frontend:/app/frontend
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: favour
      MYSQL_DATABASE: don-sanity-backend
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
